/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2026-06-20 07:18:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Clement - Task Tracker</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header {\n");
      out.write("            text-align: center;\n");
      out.write("            color: white;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header h1 {\n");
      out.write("            font-size: 2.5em;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a, .nav button {\n");
      out.write("            padding: 12px 25px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 16px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-primary, .nav button.btn-primary {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-primary:hover, .nav button.btn-primary:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-secondary, .nav button.btn-secondary {\n");
      out.write("            background-color: #2196F3;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-secondary:hover, .nav button.btn-secondary:hover {\n");
      out.write("            background-color: #0b7dda;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 30px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero {\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 50px 30px;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero h2 {\n");
      out.write("            font-size: 2em;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero p {\n");
      out.write("            font-size: 1.2em;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            opacity: 0.9;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .features {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card {\n");
      out.write("            background-color: rgba(255, 255, 255, 0.1);\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            backdrop-filter: blur(10px);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card h3 {\n");
      out.write("            color: white;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-card p {\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\n");
      out.write("            font-size: 0.95em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .footer {\n");
      out.write("            text-align: center;\n");
      out.write("            color: white;\n");
      out.write("            padding: 20px;\n");
      out.write("            opacity: 0.8;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"header\">\n");
      out.write("            <h1>📋 Clement Task Tracker</h1>\n");
      out.write("            <p>Collaborate and manage project tasks efficiently</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"nav\">\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/tasks\" class=\"btn-secondary\">View Tasks</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/task-form.jsp\" class=\"btn-primary\">Create Task</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"card hero\">\n");
      out.write("            <h2>Welcome to Task Tracker</h2>\n");
      out.write("            <p>Streamline your team's workflow with a simple, intuitive task management system.</p>\n");
      out.write("            \n");
      out.write("            <div class=\"features\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>✅ Create Tasks</h3>\n");
      out.write("                    <p>Add tasks with names, descriptions, due dates, and assignees</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>📊 Track Status</h3>\n");
      out.write("                    <p>Monitor task progress with status tracking and automatic due date alerts</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>🔄 Update & Delete</h3>\n");
      out.write("                    <p>Modify task details or remove completed tasks easily</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>🔍 Filter & Sort</h3>\n");
      out.write("                    <p>Organize tasks by status, assignee, or due date</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>💾 Persistent Storage</h3>\n");
      out.write("                    <p>Your tasks are saved across sessions for continuity</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <h3>👥 Team Collaboration</h3>\n");
      out.write("                    <p>Assign tasks and track team member responsibilities</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div style=\"margin-top: 30px;\">\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/tasks\" class=\"btn-primary\" style=\"padding: 15px 40px; font-size: 1.1em;\">Get Started</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <p>&copy; 2024 Clement Task Tracker. Built with Java, JSP & Servlets.</p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
