/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2026-06-20 07:19:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.clement.model.Task;
import java.time.LocalDate;

public final class task_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.clement.model.Task");
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Task List - Clement Task Tracker</title>\n");
      out.write("    <style>\n");
      out.write("        * {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header {\n");
      out.write("            text-align: center;\n");
      out.write("            color: white;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .header h1 {\n");
      out.write("            font-size: 2.5em;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 15px;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a, .nav button {\n");
      out.write("            padding: 12px 25px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-size: 16px;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-primary, .nav button.btn-primary {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-primary:hover, .nav button.btn-primary:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-secondary, .nav button.btn-secondary {\n");
      out.write("            background-color: #2196F3;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .nav a.btn-secondary:hover, .nav button.btn-secondary:hover {\n");
      out.write("            background-color: #0b7dda;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filters-card {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n");
      out.write("            gap: 15px;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group label {\n");
      out.write("            display: block;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 2px solid #e0e0e0;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-group select:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons button {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons .btn-apply {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons .btn-apply:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons .btn-clear {\n");
      out.write("            background-color: #999;\n");
      out.write("            color: white;\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .filter-buttons .btn-clear:hover {\n");
      out.write("            background-color: #777;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .tasks-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-card {\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("            border-left: 5px solid #667eea;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-name {\n");
      out.write("            font-size: 1.3em;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-description {\n");
      out.write("            color: #666;\n");
      out.write("            font-size: 0.95em;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("            line-height: 1.4;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-meta {\n");
      out.write("            font-size: 0.85em;\n");
      out.write("            color: #999;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-status {\n");
      out.write("            display: inline-block;\n");
      out.write("            padding: 6px 12px;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("            font-size: 0.85em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-pending {\n");
      out.write("            background-color: #fff3cd;\n");
      out.write("            color: #856404;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-in-progress {\n");
      out.write("            background-color: #cfe2ff;\n");
      out.write("            color: #084298;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-completed {\n");
      out.write("            background-color: #d1e7dd;\n");
      out.write("            color: #0f5132;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-on-hold {\n");
      out.write("            background-color: #f8d7da;\n");
      out.write("            color: #842029;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-due-next-week {\n");
      out.write("            background-color: #ffeaea;\n");
      out.write("            color: #a82a2a;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-late {\n");
      out.write("            background-color: #f8d7da;\n");
      out.write("            color: #842029;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-assignee {\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #667eea;\n");
      out.write("            margin-bottom: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .task-actions {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 8px;\n");
      out.write("            margin-top: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-action {\n");
      out.write("            flex: 1;\n");
      out.write("            padding: 8px 12px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: 600;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("            transition: all 0.3s;\n");
      out.write("            text-decoration: none;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-edit {\n");
      out.write("            background-color: #2196F3;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-edit:hover {\n");
      out.write("            background-color: #0b7dda;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-delete {\n");
      out.write("            background-color: #f44336;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-delete:hover {\n");
      out.write("            background-color: #da190b;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state {\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 40px;\n");
      out.write("            background-color: white;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state h2 {\n");
      out.write("            color: #999;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .empty-state p {\n");
      out.write("            color: #bbb;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error {\n");
      out.write("            color: #e74c3c;\n");
      out.write("            background-color: #fadbd8;\n");
      out.write("            padding: 12px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            border-left: 4px solid #e74c3c;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal {\n");
      out.write("            display: none;\n");
      out.write("            position: fixed;\n");
      out.write("            z-index: 1000;\n");
      out.write("            left: 0;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            background-color: rgba(0, 0, 0, 0.5);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal.show {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-content {\n");
      out.write("            background-color: white;\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.3);\n");
      out.write("            max-width: 600px;\n");
      out.write("            width: 90%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header {\n");
      out.write("            font-size: 1.5em;\n");
      out.write("            font-weight: 700;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-body {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group label {\n");
      out.write("            display: block;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #333;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input,\n");
      out.write("        .form-group select,\n");
      out.write("        .form-group textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            border: 2px solid #e0e0e0;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-family: inherit;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group input:focus,\n");
      out.write("        .form-group select:focus,\n");
      out.write("        .form-group textarea:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: #667eea;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-buttons {\n");
      out.write("            display: flex;\n");
      out.write("            gap: 10px;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-buttons button {\n");
      out.write("            padding: 10px 20px;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            font-weight: 600;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-save {\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-save:hover {\n");
      out.write("            background-color: #45a049;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-cancel {\n");
      out.write("            background-color: #999;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-cancel:hover {\n");
      out.write("            background-color: #777;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"header\">\n");
      out.write("            <h1>📋 Task List</h1>\n");
      out.write("            <p>Manage and track all your project tasks</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"nav\">\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\" class=\"btn-secondary\">Home</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/task-form.jsp\" class=\"btn-primary\">+ Create Task</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            String error = request.getParameter("error");
            if (error != null && !error.isEmpty()) {
        
      out.write("\n");
      out.write("            <div class=\"error\">\n");
      out.write("                ");
      out.print( error );
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");

            }

            @SuppressWarnings("unchecked")
            List<Task> tasks = (List<Task>) request.getAttribute("tasks");
            @SuppressWarnings("unchecked")
            List<String> assignees = (List<String>) request.getAttribute("assignees");
            @SuppressWarnings("unchecked")
            List<String> statuses = (List<String>) request.getAttribute("statuses");
            String currentFilterStatus = (String) request.getAttribute("currentFilterStatus");
            String currentFilterAssignee = (String) request.getAttribute("currentFilterAssignee");
            String currentSort = (String) request.getAttribute("currentSort");
        
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"filters-card\">\n");
      out.write("            <h3 style=\"margin-bottom: 15px;\">Filters & Sorting</h3>\n");
      out.write("            <form method=\"get\" action=\"");
      out.print( request.getContextPath() );
      out.write("/tasks\">\n");
      out.write("                <div class=\"filter-group\">\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"status\">Filter by Status</label>\n");
      out.write("                        <select id=\"status\" name=\"status\">\n");
      out.write("                            <option value=\"\">-- All Statuses --</option>\n");
      out.write("                            ");

                                if (statuses != null) {
                                    for (String status : statuses) {
                            
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print( status );
      out.write('"');
      out.write(' ');
      out.print( (currentFilterStatus != null && currentFilterStatus.equals(status)) ? "selected" : "" );
      out.write(">\n");
      out.write("                                            ");
      out.print( status );
      out.write("\n");
      out.write("                                        </option>\n");
      out.write("                            ");

                                    }
                                }
                            
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"assignee\">Filter by Assignee</label>\n");
      out.write("                        <select id=\"assignee\" name=\"assignee\">\n");
      out.write("                            <option value=\"\">-- All Assignees --</option>\n");
      out.write("                            ");

                                if (assignees != null) {
                                    for (String assignee : assignees) {
                            
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print( assignee );
      out.write('"');
      out.write(' ');
      out.print( (currentFilterAssignee != null && currentFilterAssignee.equals(assignee)) ? "selected" : "" );
      out.write(">\n");
      out.write("                                            ");
      out.print( assignee );
      out.write("\n");
      out.write("                                        </option>\n");
      out.write("                            ");

                                    }
                                }
                            
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"sortBy\">Sort By</label>\n");
      out.write("                        <select id=\"sortBy\" name=\"sortBy\">\n");
      out.write("                            <option value=\"\">-- Default --</option>\n");
      out.write("                            <option value=\"dueDate\" ");
      out.print( (currentSort != null && currentSort.equals("dueDate")) ? "selected" : "" );
      out.write(">Due Date</option>\n");
      out.write("                            <option value=\"creationDate\" ");
      out.print( (currentSort != null && currentSort.equals("creationDate")) ? "selected" : "" );
      out.write(">Creation Date</option>\n");
      out.write("                            <option value=\"status\" ");
      out.print( (currentSort != null && currentSort.equals("status")) ? "selected" : "" );
      out.write(">Status</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"filter-buttons\">\n");
      out.write("                    <button type=\"submit\" class=\"btn-apply\">Apply Filters</button>\n");
      out.write("                    <button type=\"button\" class=\"btn-clear\" onclick=\"window.location.href='");
      out.print( request.getContextPath() );
      out.write("/tasks'\">Clear Filters</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            if (tasks == null || tasks.isEmpty()) {
        
      out.write("\n");
      out.write("            <div class=\"empty-state\">\n");
      out.write("                <h2>📭 No Tasks Yet</h2>\n");
      out.write("                <p>Create your first task to get started!</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/task-form.jsp\" class=\"btn-primary\" style=\"padding: 12px 25px; border-radius: 5px; text-decoration: none; display: inline-block;\">Create First Task</a>\n");
      out.write("            </div>\n");
      out.write("        ");

            } else {
        
      out.write("\n");
      out.write("            <div class=\"tasks-grid\">\n");
      out.write("                ");

                    for (Task task : tasks) {
                        String statusClass = "status-pending";
                        if ("In Progress".equals(task.getStatus())) {
                            statusClass = "status-in-progress";
                        } else if ("Completed".equals(task.getStatus())) {
                            statusClass = "status-completed";
                        } else if ("On Hold".equals(task.getStatus())) {
                            statusClass = "status-on-hold";
                        } else if ("Due Next Week".equals(task.getStatus())) {
                            statusClass = "status-due-next-week";
                        } else if ("Late".equals(task.getStatus())) {
                            statusClass = "status-late";
                        }
                
      out.write("\n");
      out.write("                    <div class=\"task-card\">\n");
      out.write("                        <div class=\"task-name\">");
      out.print( task.getName() );
      out.write("</div>\n");
      out.write("                        ");
 if (task.getDescription() != null && !task.getDescription().isEmpty()) { 
      out.write("\n");
      out.write("                            <div class=\"task-description\">");
      out.print( task.getDescription() );
      out.write("</div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        <div class=\"task-assignee\">👤 ");
      out.print( task.getAssignee() );
      out.write("</div>\n");
      out.write("                        <div class=\"task-status ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( task.getStatus() );
      out.write("</div>\n");
      out.write("                        <div class=\"task-meta\">\n");
      out.write("                            <div>📅 Created: ");
      out.print( task.getCreationDate() );
      out.write("</div>\n");
      out.write("                            ");
 if (task.getDueDate() != null) { 
      out.write("\n");
      out.write("                                <div>⏰ Due: ");
      out.print( task.getDueDate() );
      out.write("</div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"task-actions\">\n");
      out.write("                            <button type=\"button\" class=\"btn-action btn-edit\" onclick=\"editTask('");
      out.print( task.getId() );
      out.write("', '");
      out.print( task.getName().replace("'", "\\'") );
      out.write("', '");
      out.print( task.getDescription() != null ? task.getDescription().replace("'", "\\'") : "" );
      out.write("', '");
      out.print( task.getDueDate() );
      out.write("', '");
      out.print( task.getAssignee().replace("'", "\\'") );
      out.write("', '");
      out.print( task.getStatus() );
      out.write("')\">Edit</button>\n");
      out.write("                            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/delete-task\" method=\"POST\" style=\"flex: 1; margin: 0;\">\n");
      out.write("                                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( task.getId() );
      out.write("\">\n");
      out.write("                                <button type=\"submit\" class=\"btn-action btn-delete\" onclick=\"return confirm('Are you sure you want to delete this task?');\">Delete</button>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Edit Task Modal -->\n");
      out.write("    <div id=\"editModal\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">Edit Task</div>\n");
      out.write("            <form id=\"editForm\" action=\"");
      out.print( request.getContextPath() );
      out.write("/update-task\" method=\"POST\">\n");
      out.write("                <input type=\"hidden\" id=\"taskId\" name=\"id\">\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editName\">Task Name *</label>\n");
      out.write("                    <input type=\"text\" id=\"editName\" name=\"name\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editDescription\">Description</label>\n");
      out.write("                    <textarea id=\"editDescription\" name=\"description\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editDueDate\">Due Date</label>\n");
      out.write("                    <input type=\"date\" id=\"editDueDate\" name=\"dueDate\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editAssignee\">Assignee *</label>\n");
      out.write("                    <input type=\"text\" id=\"editAssignee\" name=\"assignee\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"editStatus\">Status</label>\n");
      out.write("                    <select id=\"editStatus\" name=\"status\">\n");
      out.write("                        <option value=\"\">-- Select Status --</option>\n");
      out.write("                        <option value=\"Pending\">Pending</option>\n");
      out.write("                        <option value=\"In Progress\">In Progress</option>\n");
      out.write("                        <option value=\"Completed\">Completed</option>\n");
      out.write("                        <option value=\"On Hold\">On Hold</option>\n");
      out.write("                        <option value=\"Due Next Week\">Due Next Week</option>\n");
      out.write("                        <option value=\"Late\">Late</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-buttons\">\n");
      out.write("                    <button type=\"button\" class=\"btn-cancel\" onclick=\"closeEditModal()\">Cancel</button>\n");
      out.write("                    <button type=\"submit\" class=\"btn-save\">Save Changes</button>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function editTask(id, name, description, dueDate, assignee, status) {\n");
      out.write("            document.getElementById('taskId').value = id;\n");
      out.write("            document.getElementById('editName').value = name;\n");
      out.write("            document.getElementById('editDescription').value = description;\n");
      out.write("            document.getElementById('editDueDate').value = dueDate;\n");
      out.write("            document.getElementById('editAssignee').value = assignee;\n");
      out.write("            document.getElementById('editStatus').value = status;\n");
      out.write("            document.getElementById('editModal').classList.add('show');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function closeEditModal() {\n");
      out.write("            document.getElementById('editModal').classList.remove('show');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        window.onclick = function(event) {\n");
      out.write("            var modal = document.getElementById('editModal');\n");
      out.write("            if (event.target == modal) {\n");
      out.write("                modal.classList.remove('show');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
